Distance.MVC/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Autofac;
using Distance.Business;
using Distance.Business.Entitiy;
using Distance.Business.Interfaces;
using Distance.EntityFrame;
using Distance.EntityFrame.Repository;
using Distance.MVC.Helpers;
using Omu.ValueInjecter;
using Distance.GoogleConsumer;
using System.Configuration;
using System.Net;
using System.Threading;

namespace Distance.MVC.Controllers
{
    public class ContactController : MyController
    {

        public ActionResult Index()
        {
            if (ConfigurationManager.AppSettings["DontCheckFirewallAtHome"] != "true")
                try
                {
                    Geocoder.GetLocation("London");
                }
                catch (Exception ex)
                {
                    ViewBag.FirewallException = ex.Message;
                }

            var list = _contactRepository
                            .All
                            .ToList();

            return View(list );
        }

        public ActionResult Edit(int id = 0)
        {
            var contact = _contactRepository.Get(id) ?? new Contact();
            contact.DistanceComparisons = _discoRepository.Find(x => x.Customer.ContactId == id).ToList(); 

            ViewBag.marker = "Content/" + ( contact.ExistingMarker() ?? "Markers/dots/red-dot.png" );

            return View( contact );
        }

        [HttpPost]
        public ActionResult Edit(Contact contact)
        {
            if (contact.ContactId != 0)
                _contactRepository.Update(contact);
            else 
                _contactRepository.Save(contact);
                
            var postcodes = Request["postcodes"].Split(new[] { Environment.NewLine }, StringSplitOptions.None);

            contact.Addresses = _addressRepository.Find(a => a.Contact.ContactId == contact.ContactId).ToList(); 
            contact.UpdateAddressesByPostcodes(
                postcodes, 
                Request["CountryValidator"], 
                _contactRepository, 
                _addressRepository );

            foreach (var address in contact.Addresses.Where(a => a.Lat == null))
            {
                try
                {
                    var location = Geocoder.GetLocation(address.PostCode);
                    address.Lat = location.Lat;
                    address.Lng = location.Lng;
                    _addressRepository.Save(address);
                }
                catch 
                {
                    if (contact.InvalidPostCodes == null)  
                        contact.InvalidPostCodes = new List<string>();
                    contact.InvalidPostCodes.Add( address.PostCode );
                }
                Thread.Sleep(100);
            }

            if (contact.ContactType == ContactType.Enterprise)
            {
                var context = _scope.Resolve<EfUnitOfWork>();
                context.Configuration.ProxyCreationEnabled = false;
                context.Configuration.LazyLoadingEnabled = false;

                contact = _contactRepository.Find(x => x.ContactId == contact.ContactId)
                    .Include(x => x.Addresses).FirstOrDefault();

                Statics.UpdateEnterpriseRootContact(contact);
            }

            if (contact.InvalidPostCodes == null)
                return RedirectToAction("Edit", new { id = contact.ContactId }); 
            else
                return View( contact );

        }

        public ActionResult Delete(int id)
        {
            var contact = _contactRepository.Get(id) ;
            if (contact == null)
                throw new NullReferenceException("No such contact!");

            contact.Delete( _contactRepository, _addressRepository, _discoRepository, _reportRepository ); 
                
            return RedirectToAction("Index");
        }


        public ActionResult Locations(int id)
        {
//            if (!Request.IsAjaxRequest()) return new HttpStatusCodeResult(HttpStatusCode.BadRequest );
            var contact = _contactRepository.Get(id);

            var locations = contact.Addresses
                .Where(x => x.Lat != null)
                .ToList()
                .Select(x => new Address() { PostCode= x.PostCode, Lat = x.Lat, Lng = x.Lng })
                .ToList();

            return Json(locations, JsonRequestBehavior.AllowGet);
        }

    }
}

Distance.MVC/Controllers/DiscoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Hosting;
using System.Web.Mvc;
using Autofac;
using Distance.Business.Entitiy;
using Distance.Business.Helpers;
using Distance.Business.Interfaces;
using Distance.EntityFrame;
using Distance.GoogleConsumer;
using Distance.MVC.Helpers;
using WebGrease.Css.Extensions;
using System.Web.Script.Serialization;
using Distance.Business;

namespace Distance.MVC.Controllers
{

    public class DiscoController : MyController
    {
        public static string _reportsDumpDirectory; 
        public DiscoController()
        {
            _reportsDumpDirectory = _reportsDumpDirectory ?? 
                ( String.IsNullOrEmpty(ConfigurationManager.AppSettings["ReportsDumpDirectory"])
                     ? new DirectoryInfo(HostingEnvironment.ApplicationPhysicalPath).Parent.FullName + @"\DiscoDump\" 
                     : ConfigurationManager.AppSettings["ReportsDumpDirectory"] );

            if (! Directory.Exists(_reportsDumpDirectory)) Directory.CreateDirectory(_reportsDumpDirectory); 
        }

        public ActionResult DeleteReport(int id)
        {
            var report = _reportRepository.Get(id);
            var discoId = report.DistanceComparison.DistanceComparisonId;
            _reportRepository.Delete( report  );
            return RedirectToAction("DetailsForId", new { id = discoId}); 
        }

        public ActionResult Details(string competitorIds, int customerId )
        {
            var arrCompetitorIds = competitorIds.Split(',').Where( x=> x.IsNumeric() )
                .Select( int.Parse ).ToArray();

            var disco = _discoRepository.Find(x => x.Customer.ContactId == customerId
                    && x.CompetitorsIncluded.All(y => arrCompetitorIds.Contains(y.ContactId))
                    && x.CompetitorsIncluded.Count == arrCompetitorIds.Count()).FirstOrDefault();

            if (disco == null)
            {
                disco = new DistanceComparison()
                {
                    Customer = _contactRepository.Get(customerId),
                    CompetitorsIncluded = new List<Contact>()
                };
                arrCompetitorIds.ForEach( c=> disco.CompetitorsIncluded.Add( _contactRepository.Get(c ) ) );
                _discoRepository.Save(disco);
            }

            return View( disco );
        }

        public ActionResult DetailsForId( int id )
        {
            var disco = _discoRepository.Get(id);
            return View( "Details", disco );
        }


        public ActionResult Report(int id)
        {
            var report = _reportRepository.Get(id);

            report.CustomerWithDistances = BinaryDeserializer<Contact>.Deserialize(
                report.Serialized_Contact_Customer 
                ?? System.IO.File.ReadAllBytes(_reportsDumpDirectory + @"\" + id));

            if (report.Serialized_ICollectionFetcherLogForTarget != null )
                report.Log = BinaryDeserializer<ICollection<ComparisonReport.LogForTarget>>.Deserialize(report.Serialized_ICollectionFetcherLogForTarget);


            var xiCompetitorsWithoutMarkerCount = -1;
            var markerColors = new string[] {"pink", "orange", "purple", "blue", "green", "red"};
            var compeditorMarkers = new Dictionary<int, string>();
            
            foreach (var contact in report.DistanceComparison.CompetitorsIncluded)
                compeditorMarkers[contact.ContactId] = contact.ExistingMarker() ?? ((Func<string>)(() =>
                {
                    xiCompetitorsWithoutMarkerCount++;
                    return String.Format("Markers/dots/{0}-dot.png", markerColors[xiCompetitorsWithoutMarkerCount]);
                }))(); 

            var jsonLinq = report.CustomerWithDistances.Addresses.Where( a=> a.SpansToTargets != null ).Select(a => new
            {
                CustomerAddressId = a.AddressId,
                CustomerAddressLat = a.Lat,
                CustomerAddressLng = a.Lng,
                CustomerAddressPostCode = a.PostCode,
                SpansToEnterprise = a.SpansToTargets.FirstOrDefault(x => x.Destination.ContactId == Statics.EnterpriseRootContact.ContactId)
                    .Spans.OrderByDescending(x => x.Error == null).ThenBy(x => x.Meter).Take(5)
                    .Select( es => new { 
                        es.Destination.AddressId,
                        es.Destination.PostCode,
                        es.Destination.Lat,
                        es.Destination.Lng,
                        Distance = es.Meter.MetersToMiles(),
                        es.Error
                    } ),
                SpansToCompetitors = a.SpansToTargets.Where(x => x.Destination.ContactId != Statics.EnterpriseRootContact.ContactId)
                    .Select(cs => new
                    {
                        CompetitorContactId = cs.Destination.ContactId,
                        Icon = compeditorMarkers[cs.Destination.ContactId],
                        CompetitorName = cs.Destination.Name,
                        SpansTo = cs.Spans.OrderByDescending(x => x.Error == null).ThenBy(x => x.Meter).Take(5)
                            .Select(x => new
                            {
                                x.Destination.AddressId,
                                x.Destination.PostCode,
                                x.Destination.Lat,
                                x.Destination.Lng,
                                Distance = x.Meter.MetersToMiles(),
                                x.Error
                            })
                    })
            });
            ViewBag.json = new JavaScriptSerializer().Serialize(jsonLinq);


            var averageDistances = new Dictionary<int, int?>();

            averageDistances.Add( 
                Statics.EnterpriseRootContact.ContactId, 
                (int?)report.CustomerWithDistances.Addresses.Where(x => x.SpansToTargets != null).SelectMany(
                      x => x.SpansToTargets.Where(y => y.Destination.ContactId == Statics.EnterpriseRootContact.ContactId))
                      .Select(x => x.Spans.Min(y => y.Meter)).Average() );
            
            foreach (var competitor in report.DistanceComparison.CompetitorsIncluded)
                averageDistances.Add( 
                    competitor.ContactId, 
                    (int?) report.CustomerWithDistances.Addresses.Where(x => x.SpansToTargets != null).SelectMany(
                        x => x.SpansToTargets.Where(y => y.Destination.ContactId == competitor.ContactId))
                        .Select(x => x.Spans.Min(y => y.Meter)).Average());

            ViewBag.averageDistances = averageDistances;
            ViewBag.minimumDistance = averageDistances.Min(x => x.Value);

            return View( report );
        }

        public ActionResult NewReportForDisco( int id  )
        {
            var context = _scope.Resolve<EfUnitOfWork>();
            context.Configuration.ProxyCreationEnabled = false;
            context.Configuration.LazyLoadingEnabled = false;

            var disco = _discoRepository.Find(x => x.DistanceComparisonId == id)
                .Include(x => x.Customer)
                .Include(x => x.CompetitorsIncluded)
                .FirstOrDefault();

            disco.Customer = _contactRepository.Find(x => x.ContactId == disco.Customer.ContactId)
                .Include(x => x.Addresses).FirstOrDefault();

            disco.CompetitorsIncluded = disco.CompetitorsIncluded.Select(q => _contactRepository.Find(x => x.ContactId == q.ContactId)
                    .Include(x => x.Addresses).FirstOrDefault()).ToList();


            var fetcher = new ComparisonReportFetcher(
                reportsDumpDirectory : _reportsDumpDirectory, 
                discoWithoutProxies: disco,
                contactRepo: _contactRepository,
                reportRepo: _reportRepository,
                waitAfterRequest: int.Parse(ConfigurationManager.AppSettings["Google.Distance.WaitAfterRequest"]),
                dimensionSize: int.Parse(ConfigurationManager.AppSettings["Google.Distance.DimensionSize"])
                );

            new Thread(() => fetcher.Fetch()).Start();

            return Json(new { ComparisonReportId = fetcher.ComparisonReportId }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProgressStatusForReport( int id )
        {

            var report = _reportRepository.Get(id);

            var result = new {
                report.NoReplyError, 
                PercentageCompleted = report.PercentageCompleted()
            };

            return Json(result , JsonRequestBehavior.AllowGet);
        }


    }
}

Distance.MVC/Views/Disco/Details.cshtml
@using System.Web.UI.WebControls
@using Distance.Business
@using Distance.MVC.Controllers
@model DistanceComparison 

@{
    ViewBag.Title = "Distance Comparison";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var lastCompetitorModified = Model.CompetitorsIncluded.Max(c => c.AddressesModified);
    ViewBag.lastAddressModified =
        (new[]
        {
            lastCompetitorModified,
            Statics.EnterpriseRootContact.AddressesModified,
            Model.Customer.AddressesModified
        }).Max() ?? DateTime.MinValue;

    ViewBag.lastReport = (Model.ComparisonReports != null && Model.ComparisonReports.Count > 0 )
        ? Model.ComparisonReports.Max(c => c.Created) : DateTime.MinValue; 
    
}

<link href="~/Content/app/Disco.css" rel="stylesheet" />

<h2>&nbsp </h2>

<div class="row">
    <div class="col-md-7">
        <b>Comparison details</b>
        <div class="panel panel-default">
            <div class="panel-body">
                @Html.Partial("_ComparisonDetails", Model)
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <b>Reports in repository</b>
        <div class="panel panel-default">
            <div class="panel-body">
                <div id="myProgressbar"><div id="myProgressLabel"></div></div>
                @if (Model.ComparisonReports != null)
                {
                    <table class="table table-hover">
                        <tr>
                            <th>
                                Date created
                            </th>
                        </tr>
                        @foreach (var report in Model.ComparisonReports)
                        {
                            <tr class="@ReportExpired(report.Created)">
                                <td>
                                    <a href="@Url.Action("Report", new { id = report.ComparisonReportId })">
                                        @string.Format("{0:F}", report.Created)
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-danger btn-xs" onclick="return confirm('Are you sure?');" href="@Url.Action("DeleteReport", new { id = report.ComparisonReportId })">
                                        <span class="glyphicon glyphicon-remove"
                                              data-toggle="tooltip" data-placement="top" title="Delete that customer"></span>
                                    </a>                                    
                                </td>
                            </tr>
                        }
                    </table> 
                }
            </div>
        </div>        
        
        <span class="glyphicon glyphicon-barcode"></span>
        <i style="color:gray;font-size:small;"> @DiscoController._reportsDumpDirectory</i>
    </div>
</div>

<div class="modal fade" id="modalGoogleStopped">
    <div class="modal-dialog">
        <div class="modal-content panel-danger">
            <div class="modal-header panel-heading">
                <h4 class="modal-title" id="modalGoogleStopped-title">Google is not responding</h4>
            </div>
            <div class="modal-body">
                <p>Please try again later..&hellip;</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-warning" id="urlReport">Go to report</a>
                <button type="button" class="btn btn-danger" onclick="location.reload()">Cancel</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<style>
    .ui-progressbar {
        position: relative;
    }

    #myProgressLabel {
        position: absolute;
        left: 50%;
        top: 4px;
        font-weight: bold;
        text-shadow: 1px 1px 0 #fff;
    }
</style>


@section TopMenu{
    <div class="col-md-8">
        <a class="btn btn-default btn" href="@Url.Action("Index", "Contact")">
            Home &nbsp<span class="glyphicon glyphicon-folder-open"></span>
        </a>
    </div>
    <div class="col-md-4">
        <button class="btn btn-default btn" onclick="GetReport(@Model.DistanceComparisonId, this)" data-loading-text="Loading...">
            Generate new report &nbsp<span class="glyphicon glyphicon-cog"></span>
        </button>
    </div>
}

@section Scripts {

    <script>

        var getProgressStatusForReportUrl = "@Url.Action("GetProgressStatusForReport")/",
            myProgressbar = $("#myProgressbar"),
            myProgressLabel = $("#myProgressLabel");

        function GetReport(discoId, button) {
            $(button).button('loading');

            $.getJSON("@Url.Action("NewReportForDisco")/" + discoId, null,
                function(newReportForDisco) {
                    getProgressStatusForReportUrl += newReportForDisco.ComparisonReportId;

                    var xurl = "@Url.Action("Report")/" + newReportForDisco.ComparisonReportId;
                $("#urlReport").attr("href", xurl);

                myProgressbar.progressbar({
                    value: false,
                    complete: function () {
                        // give time to save 
                        setTimeout(NavigateAfterReportCompleted, 2000);
                    }
                });
                setTimeout(Progress, 1000);
            });
        }

        function NavigateAfterReportCompleted() {
            window.location.href = $("#urlReport").attr("href");
        }

        function Progress() {
            $.getJSON(getProgressStatusForReportUrl, null,
                function(getProgressStatusForReport) {

                    if (getProgressStatusForReport.NoReplyError != "" && getProgressStatusForReport.NoReplyError != null) {
                        $('#modalGoogleStopped-title').html(getProgressStatusForReport.NoReplyError);
                        $('#modalGoogleStopped').modal('show');
                    }

                    myProgressbar.progressbar("value", getProgressStatusForReport.PercentageCompleted);
                    myProgressLabel.text(getProgressStatusForReport.PercentageCompleted + "%");
                });
            setTimeout(Progress, 1000);
        }
    </script>
}


@helper ReportExpired(DateTime report)
{
    if (report < ViewBag.lastAddressModified)
    {<text>danger</text>}
    else if (report < DateTime.Now.AddMonths(-1))
    {<text>warning</text>}
    else
    {<text>success</text>}
}

Distance.MVC/Views/Disco/Report.cshtml
@using System.Web.UI.WebControls
@using Distance.Business
@using Distance.MVC.Helpers
@using System.Configuration

@model ComparisonReport

@{
    ViewBag.Title = "Distance Comparison Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>&nbsp </h2>
<style type="text/css">
    .tableFloatingHeaderOriginal th {
        background-color: #fff;
    }
    #calculationsRow input {
        width: 50px;
        background-color: whitesmoke;
    }
    #calculationsRow td {
        white-space: nowrap;
    }
    .fuelCostOutput {
        font-weight: bold;
    }

</style>


<div class="panel panel-default">
    <table class="table table-hover" id="tableReport">
        <thead>
            <tr>
                <th></th>
                <th>@Model.CustomerWithDistances.Name <img src="../../Content/markers/dots/red-dot.png"></th>
                <th>Enterprise <img src="../../Content/markers/enterpriseRootContact.png"></th>
                @foreach (var competitor in Model.DistanceComparison.CompetitorsIncluded)
                {
                    <th id="th@(competitor.ContactId)">@competitor.Name</th>
                }
            </tr>
        </thead>
        <tbody></tbody>
        @*@foreach (var address in Model.CustomerWithDistances.Addresses)
            {
            @Html.Partial("_customerAddressInReport", address)
            }*@
        <tfoot>
            <tr class="success">
                <td></td>
                <td>Average</td>
                @foreach (KeyValuePair<int, int?> distance in ViewBag.averageDistances)
                {
                    <td>
                        @( ((int?)distance.Value).MetersToMiles() )
                    </td>
                }
            </tr>
            @if (Model.Log != null)
            {
                <tr class="danger">
                    <td></td>
                    <td></td>
                    <td>
                        @foreach (var enterpriseFail in Model.Log.FirstOrDefault(x => x.TargetContact.ContactType == ContactType.Enterprise).RequestFailureLog)
                        {
                            <div>@enterpriseFail.ExceptionMessage</div>
                        }
                    </td>
                    @foreach (var targetContact in Model.Log.Where(x => x.TargetContact.ContactType != ContactType.Enterprise))
                    {
                        <td>
                            @foreach (var compeditorFail in targetContact.RequestFailureLog)
                            {
                                <div>@compeditorFail.ExceptionMessage</div>
                            }
                        </td>
                    }
                </tr>
            }
            <tr>
                <td></td>
                <td colspan="2">Fuel D/C Mileage</td>
                @foreach (var distance in ((IDictionary<int,int?>)ViewBag.averageDistances).Skip( 1 ))
                {
                    <td>
                        @(((int?)(2*(distance.Value) ) ).MetersToMiles() )
                    </td>
                }
            </tr>
            <tr id="calculationsRow">
                <td colspan="3">
                    <div class="center-block">
                        Annual fuel cost  
                        for <input id="hiresPerYear" onchange="CalculateFuelCost()" value="@Model.DistanceComparison.Customer.HiresPerYear"> hires 
                        based on £<input id="fuelCost" onchange="CalculateFuelCost()" value="@ConfigurationManager.AppSettings["FuelCostPerMile"]"> per mile.
                    </div>
                </td>
                @foreach (var distance in ((IDictionary<int, int?>)ViewBag.averageDistances).Skip(1))
                {
                    <td class="fuelCostOutput" data-additional-miles="@(2 * distance.Value / 1609.344 )"></td>
                }

            </tr>
        </tfoot>

    </table>
</div>


<textarea class="hidden" id="textareaJson">@ViewBag.json</textarea>

<script type="template" id="tmplCustomerAddressInReport">
    <tr class="details">
        <td>
            <button class="btn btn-default btn-xs" onclick="ComparisonReport.ToggleDetails(${CustomerAddressId}, this)">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </td>
        <td>${CustomerAddressPostCode}</td>
        <td>{{tmpl(SpansToEnterprise[0]) "#tmplSpanInReport"}}</td>
        {{each SpansToCompetitors }}
        <td>{{tmpl($value.SpansTo[0]) "#tmplSpanInReport"}}</td>
        {{/each}}
    </tr>
    <tr class="details hidden" id="trDetails_${CustomerAddressId}">
        <td></td>
        <td></td>
        <td>{{tmpl(ComparisonReport.ArrayShiftByVal(SpansToEnterprise)) "#tmplSpanInReport"}}</td>
        {{each SpansToCompetitors }}
        <td>{{tmpl(ComparisonReport.ArrayShiftByVal($value.SpansTo)) "#tmplSpanInReport"}}</td>
        {{/each}}
    </tr>
    <tr class="details hidden" id="trDetailsMap_${CustomerAddressId}">
        <td></td>
        <td colspan="${SpansToCompetitors.length+2}">
            <div class="mapCanvas" id="mapCanvas_${CustomerAddressId}"></div>
        </td>
    </tr>
</script>

<script type="template" id="tmplSpanInReport">
    <div class="panel panel-default">
        <div class="panel-body">
            <span>${PostCode}</span>
            <span class="text-nowrap pull-right">
                {{if Error }}
                <span class="label label-danger">${Error}</span>
                {{else}}
                <span class="label label-default">${Distance}</span>
                {{/if}}
            </span>
        </div>
    </div>
</script>

<style>
    .details .panel-body {
        padding: 5px;
    }

    .details .panel {
        margin-bottom: 5px;
    }

    .mapCanvas {
        width: 100%;
        height: 400px;
    }
</style>


@section Scripts {

    <script src="https://maps.googleapis.com/maps/api/js?key=@ConfigurationManager.AppSettings["Google.maps.javascript.apiKey"]"></script>
    <script src="~/Scripts/app/ComparisonReport.js"></script>
    <script src="~/Scripts/jquery.stickytableheaders.min.js"></script>
    <script>
        $(function() {
            ComparisonReport.InitFromTextarea();
            $("#tableReport").stickyTableHeaders({ fixedOffset: $(".navbar-fixed-top") });

            CalculateFuelCost();
        });

        function CalculateFuelCost() {
            $(".fuelCostOutput").each(function() {
                var xcost = $(this).data("additional-miles") * $("#hiresPerYear").val() * $("#fuelCost").val();
                $(this).html( "£"+ xcost.toFixed(2) );
            });
        }


    </script>
}

@section TopMenu{
    <div class="col-md-8">
        <a class="btn btn-default btn" href="@Url.Action("Index", "Contact")">
            Home &nbsp<span class="glyphicon glyphicon-folder-open"></span>
        </a>
        <a class="btn btn-default btn" href="@Url.Action("DetailsForId", "Disco", new { id = Model.DistanceComparison.DistanceComparisonId })">
            Distance comparison header &nbsp<span class="glyphicon glyphicon-th-list"></span>
        </a>
    </div>

}

Distance.MVC/Views/Disco/_comparisonDetails.cshtml
@using System.Web.UI.WebControls
@using Distance.Business
@model DistanceComparison

<div>
    <a href="@Url.Action("DetailsForId", "Disco", new { id = Model.DistanceComparisonId })">Comparison @Model.DistanceComparisonId</a>
</div>
<hr/>
<br/>
<ul class="contactList">
    <li>
        <a class="btn btn-default btn-xs" href="@Url.Action("Edit", "Contact", new { id = Statics.EnterpriseRootContact.ContactId })">
            <span class="glyphicon glyphicon-edit"></span>
        </a>
        <img src="~/Content/app/ban_enterpriseLogo.jpg" />
        <span class="badge">@Statics.EnterpriseRootContact.Addresses.Count</span>
        <span style="font-size: 10px;"
              class="label label-@ContactModifiedLabel(Statics.EnterpriseRootContact.AddressesModified)">
            @string.Format("{0:F}", Statics.EnterpriseRootContact.AddressesModified)
        </span>
    </li>
</ul>

<h5>Pinned customer:</h5>
<ul class="contactList">
    <li>
        <a class="btn btn-default btn-xs" href="@Url.Action("Edit", "Contact", new { id = Model.Customer.ContactId })">
            <span class="glyphicon glyphicon-edit"></span>
        </a>
        <b> @Model.Customer.Name </b>
        <span class="badge">@Model.Customer.Addresses.Count</span>
        <span style="font-size: 10px;"
              class="label label-@ContactModifiedLabel(Model.Customer.AddressesModified)">
            @string.Format("{0:F}", Model.Customer.AddressesModified)
        </span>
    </li>
</ul>
<h5>Included competitors:</h5>

<ul class="contactList">

    @foreach (var comp in Model.CompetitorsIncluded)
    {
        <li>
            <a class="btn btn-default btn-xs" href="@Url.Action("Edit", "Contact", new { id = comp.ContactId })">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            <b>@comp.Name</b>
            <span class="badge">@comp.Addresses.Count</span>
            <span style="font-size: 10px;"
                  class="label label-@ContactModifiedLabel( comp.AddressesModified )">
                @string.Format("{0:F}", comp.AddressesModified)
            </span>
        </li>
    }
</ul>
<hr style="margin-bottom:8px;"/>
<div class="pull-right text-nowrap">
    Ultimate last address modified:
    <span style="font-size: 10px;"
          class="label label-@ContactModifiedLabel(ViewBag.lastAddressModified)">
        @string.Format("{0:F}", ViewBag.lastAddressModified)
    </span>
</div>


@helper ContactModifiedLabel(DateTime? contactModified)
{
    if (contactModified < ViewBag.lastReport || contactModified == null)
    {<text>info</text>}
    else
    {<text>danger</text>}
}

Distance.MVC/Views/Disco/_spanInReport.cshtml
@using Distance.MVC.Helpers
@model Span

<div class="panel panel-default">
    <div class="panel-body">
        <span>@Model.Destination.PostCode</span>
        <span class="text-nowrap pull-right">
            @if (Model.Error == null)
            {
                <span class="label label-default">@Model.Meter.ToMiles()</span>
            }
            else
            {
                <span class="label label-danger">@Model.Error</span>
            }
        </span>
    </div>
</div>